networks:
  internal:
    driver: bridge

services:
  app:
    container_name: php-app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: php-app
    image: php:8.3.13-fpm-alpine
    volumes:
      - ./PetStore:/var/www/html
      - ./config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    env_file:
      - ./config/.env
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./PetStore/www:/var/www/html/www
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    ports:
      - "80:80"