networks:
  internal:
    driver: bridge

services:
  app:
    container_name: php-app
    build:
      context: .
      dockerfile: ./Dockerfile-integration
      target: php-app
    image: php:8.3.13-fpm-alpine
    volumes:
      - ./IntegrationTests/log:/var/www/html/log
      - ./config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    env_file:
      - ./config/.env
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./PetStore/www:/var/www/html/www
      - ./IntegrationTests/log:/var/log/nginx
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    depends_on:
      - app

  tests-php:
    build:
      context: .
      dockerfile: ./Dockerfile-integration
      target: build-test
    image: build-test
    networks:
      - internal
    depends_on:
      - nginx
    command: [ 'composer',  'run-integration-tests' ]